---
sidebar: sidebar 
permalink: concept_lic_platforms.html 
keywords: license, licensing, platform license offerings, license offerings, standard, premium, premium xl 
summary: 您可以購買三種平台容量等級的 ONTAP Select 容量層級或容量池授權。這些授權產品決定了您部署 ONTAP Select 的主機功能。 
---
= 了解 ONTAP Select 的平台授權產品
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以購買標準版、高級版或高級 XL 版的 ONTAP Select 容量層級或容量池授權。這些授權方案決定了您部署 ONTAP Select 的主機功能。



[[what-a-platform-license-offering-provides]]
== 平台授權方案提供的內容

特定授權方案決定了 Hypervisor 主機在以下兩個方面的功能：

* 執行個體類型 (CPU、記憶體)
* 附加功能


授權方案依功能遞增順序排列，從標準版到進階 XL 版。通常，您選擇的授權方案將授予您該等級及其所有較低等級的功能。例如，進階版包含進階版和標準版的所有功能。

下表比較了標準版、進階版和進階版 XL 授權的功能。

[cols="25,25,25,25,25"]
|===
2+| 授權支援… | 標準 | 高級 | 高級 XL 


2+| 執行個體類型 | 僅限小型 | 小型或中型 | 小型、中型或大型 


.2+| 硬碟機（HDD）在… | 硬體 RAID 組態 | 是的 | 是的 | 是的 


| vNAS 組態 | 是的 | 是的 | 是的 


.3+| 固態硬碟 （SSD） 在… | 硬體 RAID 組態 | 否 | 是的 | 是的 


| 軟體 RAID 組態 | 否 | 是的 | 是的 


| vNAS 組態 | 是的 | 是的 | 是的 


.3+| NVMe 磁碟機在... | 硬體 RAID 組態 | 否 | 否 | 是的 


| 軟體 RAID 組態 | 否 | 否 | 是的 


| vNAS 組態 | 是的 | 是的 | 是的 


2+| MetroCluster SDS | 否 | 是的 | 是的 
|===

NOTE: 基於核心的虛擬機器（KVM）不支援大型執行個體類型。



[[compare-hardware-support-for-platform-license-offerings]]
== 继续。

標準版、高級版和高級 XL 版授權支援多種硬體和軟體。有關硬體和軟體版本的最新資訊，請參閱 link:https://mysupport.netapp.com/matrix/["互通性對照表工具"^]。

[role="tabbed-block"]
====
.核心項目
--
[cols="5"30"]
|===


2+| 核心項目類型 3+| 說明 


2+| 主機通訊協定 3+| NFS、SMB/CIFS、iSCSI 和 NVMe over TCP 


2+| 部署選項 3+| 單節點、雙節點叢集（HA 配對）、四節點、六節點、八節點、十節點或十二節點叢集 


2+| 支援的容量 （每個節點） 3+| 高達 400TB 原始資料（ESXi 和 KVM） 
|===
--
.硬體
--
[cols="5"30"]
|===


2+| 硬體類型 3+| 說明 


2+| 執行個體大小 | 小型 | 中 | 大型 


2+| CPU 系列 | Intel Xeon E5-26xx v3 (Haswell) 或更新版本 | Intel Xeon E5-26xx v3 (Haswell) 或更新版本 | Intel Xeon E5-26xx v3 (Haswell) 或更新版本 


2+| ONTAP Select CPU / 記憶體 | 4 個虛擬 CPU（vCPU）/ 16GB RAM | 8 個 vCPU / 64GB RAM | 16 個 vCPU / 128GB RAM 


2+| 主機 CPU / 記憶體最低需求 ^1^ | 6 核心 / 24GB RAM | 10 個核心 / 72GB RAM | 18 核心 / 136GB RAM 


2+| 網路 （每個節點） 3+| 單節點叢集至少需要兩個 1GbE 連接埠 雙節點叢集（HA 配對）至少需要四個 1GbE 連接埠 四節點、六節點、八節點、十節點或十二節點叢集至少需要兩個 10GbE 連接埠 
|===
^1^ 假設 Hypervisor 使用兩個核心和 8GB RAM。

--
.儲存類型
--
下表提供指定儲存設備所需的最低授權類型。 

[cols="5"30"]
|===


2+| 儲存類型 3+| 說明 


2+| 授權類型 | 標準 | 高級 | 高級 XL 


2+| 執行個體大小 | 小型 | 小型和中型 | 小型、中型和大型 


2+| 本地 DAS 搭配硬體 RAID 控制器 | 8 - 60 個磁碟機 | 8 - 60 個磁碟機 | 8 - 60 個磁碟機 


2+| HDD （ SAS 、 NL-SAS 、 SATA ） | 不適用 | 4 – 60 個磁碟機 | 4 – 60 個磁碟機 


2+| SSD （SAS） | 不適用 | 4 – 60 個磁碟機（僅限 SSD） | 4 – 60 個磁碟機（僅限 SSD） 


2+| 本地 DAS 與軟體 RAID | 不適用 | 適用 | 4 - 14 個磁碟機（僅限 NVMe） 


2+| 外部陣列 ^1^ 3+| 託管在外部陣列上的資料存放區透過 FC、FCoE、iSCSI 和 NFS 連線（KVM 不支援 NFS）。這些資料存放區提供高可用性和恢復能力。 
|===
^1^ 外部陣列傳輸協定支援反映了網路儲存連線能力。

--
.軟體
--
[cols="5"30"]
|===


2+| 軟體類型 3+| 說明 


2+| Hypervisor 支援（VMware） 3+| VMware vSphere 9.0 VMware vSphere 8.0GA 及更新 1 至 3 VMware vSphere 7.0GA 及更新 1 至 3C 


2+| Hypervisor 支援（KVM）  a| 
Red Hat Enterprise Linux 64 位元（KVM）10.1、10.0、9.7、9.6、9.5、9.4、9.3、9.2、9.1、9.0、8.8、8.7 和 8.6

Rocky Linux (KVM) 10.1、10.0、9.7、9.6、9.5、9.4、9.3、9.2、9.1、9.0、8.9、8.8、8.7 和 8.6



2+| 管理軟體 3+| NetApp Active IQ Unified Manager 管理套件 ONTAP Select Deploy Utility SnapCenter（選用） 
|===
--
====
.接下來呢？
link:concept_lic_workflow.html["了解如何購買 ONTAP Select 授權"]
