---
sidebar: sidebar 
permalink: reference_new_ots.html 
keywords: new features 
// summary: The current release includes several new features and improvements specific to ONTAP Select. 
summary: 目前版本包含 ONTAP Select 特有的幾項新功能或改進。 
---
= ONTAP Select 的新增功能
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
了解 ONTAP Select 支援版本中的新功能和增強功能。



== ONTAP Select 9.18.1

ONTAP Select 產品下載選項的更新:: NetApp 支援網站上的 ONTAP Select 產品下載選項隨著 ONTAP Select 9.18.1 版本的發布將變更為 *ONTAP Select Deploy* 和 *ONTAP Select Image*。這兩個新的產品下載選項將取代先前的四個選項，如下表所示：
+
--
[cols="30,30,40"]
|===
| 先前產品下載選項 | 新產品下載選項 | 如需更多資訊，請前往… 


| ONTAP Select | ONTAP Select Deploy | link:task_install_deploy.html["安裝 ONTAP Select Deploy"] 


| ONTAP Select 映像安裝 | ONTAP Select 映像 | link:task_cli_deploy_image_add.html["新增 ONTAP Select 映像至 Deploy"] 


| ONTAP Select Deploy 升級 | ONTAP Select Deploy | link:task_cli_upgrade_deploy.html["升級 ONTAP Select Deploy 執行個體"] 


| ONTAP Select 節點升級 | ONTAP Select 映像 | link:concept_adm_upgrading_nodes.html["升級 ONTAP Select 節點"] 
|===
--
增強對叢集擴充與縮減的支援:: 從 ONTAP Select 9.18.1 開始，支援在 ESXi 和 KVM 虛擬機器管理程式主機上，四節點和十二節點 ONTAP Select 叢集之間進行叢集擴充和收縮。
+
--
--
您可以依下列增量增加 ESXi 或 KVM 主機上現有叢集的叢集大小：

* 從四個節點到六個、八個、十個或十二個節點
* 從六個節點到八個、十個或十二個節點
* 從八個節點到十個或十二個節點
* 從 10 到 12 個節點


您可以依下列增量減少 ESXi 或 KVM 主機上現有叢集的叢集大小：

* 從十二個節點到十個、八個、六個或四個節點
* 從十個節點到八個、六個或四個節點
* 從八個節點到六個或四個節點
* 從六個節點到四個節點


--
link:task_cluster_expansion_contraction.html["了解叢集擴充和收縮以及支援的 KVM 和 ESXi Hypervisor 版本"]。

--
更新了 KVM Hypervisor 支援:: 從 ONTAP Select 9.18.1 開始，Rocky Linux 10.1 支援 KVM Hypervisor。




== ONTAP Select 9.17.1

KVM 主機上本機連接的 NVMe 磁碟的軟體 RAID 支援:: ONTAP Select 9.17.1 為基於核心的虛擬機器（KVM）Hypervisor 主機上的 ONTAP Select 本機連接 NVMe 磁碟引入了軟體 RAID 支援。
+
--
若要對本機連線的 NVMe 磁碟使用軟體 RAID，您需要在準備 KVM 主機時link:kvm-host-configuration-and-preparation-checklist.html["配置 PCI 直通（DirectPath IO）"]。這可為 KVM 主機提供對本機連線 NVMe 磁碟的直接存取權限，這是執行下列工作所需的：

* 設定 KVM 主機以使用 NVMe 磁碟機
* 在部署叢集後使用軟體 RAID


link:concept_stor_swraid_local.html["了解本機附加儲存設備的軟體 RAID 組態服務"]。

--
支援在 KVM 主機上擴充和縮減叢集:: 從 ONTAP Select 9.17.1 開始，叢集擴充和收縮功能同時支援 Kernel-Based Virtual Machine（KVM）和 ESXi Hypervisor 主機。對於 ONTAP Select 9.16.1 和 9.15.1，叢集擴充和收縮功能僅支援 ESXi Hypervisor 主機。
+
--
您可以使用現有 ONTAP Select 叢集的叢集擴充和收縮功能，將叢集規模從六節點叢集增加到八節點叢集，或將叢集規模從八節點叢集減少到六節點叢集。

link:task_cluster_expansion_contraction.html["了解叢集擴充和收縮以及支援的 KVM 和 ESXi Hypervisor 版本"]。

--
增強對 ESXi 主機上叢集擴充與縮減的支援:: 從 ONTAP Select 9.17.1 開始,ESXi 主機上的六節點叢集和十二節點叢集之間支援叢集擴展和收縮:
+
--
--
您可以按以下增量增加現有 ESXi 叢集的叢集大小：

* 從六個節點到八個、十個或十二個節點
* 從八個節點到十個或十二個節點
* 從 10 到 12 個節點


您可以按以下增量減小現有 ESXi 叢集的叢集大小：

* 從十二個節點到十個、八個或六個節點
* 從十個節點到八個或六個節點
* 從八個節點到六個節點


--
link:task_cluster_expansion_contraction.html["了解叢集擴充和收縮以及支援的 KVM 和 ESXi Hypervisor 版本"]。

--
支援 SnapMirror 雲端:: 從 ONTAP Select 9.17.1 開始，ONTAP Select 支援 SnapMirror 雲端。SnapMirror 雲端是授權的 ONTAP 功能，當您部署 ONTAP Select 9.17.1 叢集或將現有 ONTAP Select 叢集升級至 9.17.1 版本時，預設會啟用此功能。
+
--
https://docs.netapp.com/us-en/ontap/concepts/snapmirror-cloud-backups-object-store-concept.html["了解 SnapMirror 雲端備份到物件儲存"^]。

--
支援 SnapLock Select:: 從 ONTAP Select 9.17.1 開始，新部署會自動授權 SnapLock Select（包括防篡改 Snapshot 鎖定）。若要從 ONTAP Select 9.16.1 及更早版本升級，您可以從link:https://mysupport.netapp.com/site/["NetApp 支援網站"^]免費下載 SnapLock Select 授權並手動套用。如需詳細資訊，請參閱link:reference_lic_ontap_features.html#enabled-ontap-features["ONTAP 功能預設自動啟用"]。
支援多節點叢集上的 vSAN ESA:: 從 ONTAP Select 9.17.1 開始，vSAN Express Storage Architecture（ESA）的支援範圍擴大到部署多節點叢集。此增強功能可讓您部署 vSAN ESA 組態。
+
--
vSAN ESA 是 ESXi 特有的配置，也是 VMware vSAN 在 vSphere 8 中引入的一種新架構。vSAN ESA 旨在提供更高的效率、可擴展性和效能，尤其是在使用基於 NVMe 的 TLC 快閃記憶體裝置時。

ONTAP Select Deploy 和 ONTAP Select for ESXi 支援配置 ONTAP Select 單節點和多節點叢集，其儲存資源池可以使用 vSAN 或外部陣列類型的資料存放區。

[NOTE]
====
若要執行內容庫操作，您需要額外的權限等級存取權。如果您在 vSAN ESA 部署中使用受限角色，則必須具備此權限。

link:https://docs.netapp.com/us-en/ontap-select/reference_plan_dep_vmware.html["了解內容庫作業的存取權限層級"^]。

====
--
更新的 NDA 驅動程式支援:: 從 ONTAP Select 9.17.1 開始，FreeBSD NDA（NVMe Direct Access）裝置驅動程式取代了 NVD（NVMe express disk driver）。FreeBSD 驅動程式透過實作 NVMe 命令協定來支援直接存取裝置。部署 ONTAP Select 9.17.1 叢集或將現有 ONTAP Select 叢集升級至 9.17.1 版本時，設定 NVMe 裝置時預設會啟動 FreeBSD 驅動程式。
+
--
對於 ONTAP Select 9.16.1 及更早版本，NVD 將繼續為 ONTAP Select 部署中的 NVMe 裝置提供支援。

--
更新了 KVM Hypervisor 支援:: 從 ONTAP Select 9.17.1 開始，Red Hat Enterprise Linux（RHEL）10.1、10.0、9.7 和 9.6 以及 Rocky Linux 10.0、9.7 和 9.6 支援 KVM 虛擬機器管理程式。
+
--
[NOTE]
====
在 RHEL 10.1 和 10.0 以及 Rocky Linux 10.0 主機上，KVM 虛擬機器管理程式的軟體 RAID 工作流程有一些限制。如需更多資訊，請參閱以下知識庫文章：

* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4020["CDEPLOY-4020：ONTAP Select Deploy：使用 RHEL 10 和 ROCKY 10 建立叢集 HWR 時出現警告訊息"^]
* link:https://kb.netapp.com/on-prem/ontap/ontap-select/Select-Issues/CDEPLOY-4025["CDEPLOY-4025：ONTAP Select DeployGUI：在執行 RHEL10/Rocky 10 的主機上，叢集建立頁面中 SWR 的儲存資源池和儲存磁碟不可見"^]


====
--
增強型 VMware ESXi 支援:: ONTAP Select 9.17.1 包含對 VMware ESXi 9.0 的支援。




== ONTAP Select 9.16.1

更新的 NetApp 授權檔案支援:: 從 ONTAP Select 9.16.1 開始，NetApp 授權檔案（NLF）支援已更新。新的 NLF 格式包含 ARP、ONTAP S3 和 S3 SnapMirror 功能的授權。link:reference_lic_ontap_features.html#enabled-ontap-features["深入瞭解"]。
+
--
對於新部署的 ONTAP Select 9.16.1 Deploy，系統會自動套用新的 NLF 格式。當您將現有的 ONTAP Select Deploy 升級至 9.16.1 時，不會套用新的 NLF 格式。若要取得 ARP、ONTAP S3 和 S3 SnapMirror 功能授權，您必須在升級後下載更新的 NLF。如果您還原至 ONTAP Select 9.15.1 或更早版本，則必須重新安裝升級前的功能授權。

--
支援 Autonomous Ransomware Protection:: ONTAP Select 9.16.1 引入了對自主勒索軟體防護（ARP）的支援。ONTAP Select 9.16.1 僅支援 ARP 的手動更新，不支援自動更新。ARP 功能授權包含在 ONTAP Select 9.16.1 的 NLF 中。link:reference_lic_ontap_features.html#enabled-ontap-features["深入瞭解"]。
增強型 VMware ESXi 支援:: ONTAP Select 9.16.1 包含對 VMware ESXi 8.0 U3 的支援。
更新了 KVM Hypervisor 支援:: 從 ONTAP Select 9.16.1 開始，RHEL 9.5 和 Rocky Linux 9.5 支援 KVM Hypervisor。




== ONTAP Select 9.15.1

更新了 KVM Hypervisor 支援:: 從 ONTAP Select 9.15.1 開始，RHEL 9.4 和 Rocky Linux 9.4 支援 Kernel-Based Virtual Machine（KVM）Hypervisor。
支援叢集擴充與縮減:: 從 ONTAP Select 9.15.1 開始、支援叢集擴充和縮減。
+
--
* 叢集從六節點叢集擴充至八節點叢集
+
您可以使用叢集擴展功能將叢集規模從六節點叢集擴展到八節點叢集。目前不支援從一節點、兩節點或四節點叢集擴展到六節點或八節點叢集。link:task_cluster_expansion_contraction.html#expand-the-cluster["深入瞭解"].

* 叢集收縮八節點至六節點叢集
+
您可以使用叢集收縮功能，將叢集規模從八節點叢集縮減為六節點叢集。目前不支援將六節點或八節點叢集收縮為一、二或四節點叢集。link:task_cluster_expansion_contraction.html#contract-the-cluster["深入瞭解"]。



--



NOTE: 叢集擴充和縮減的支援僅限於 ESXi 叢集。



== ONTAP Select 9.14.1

支援 KVM Hypervisor:: 從 ONTAP Select 9.14.1 開始，已復原對 KVM Hypervisor 的支援。先前，ONTAP Select 9.10.1 移除了在 KVM Hypervisor 上部署新叢集的支援，而 ONTAP Select 9.11.1 則移除了對現有 KVM 叢集和主機的管理支援（離線或刪除除外）。
不再支援部署 VMware vCenter 外掛程式:: 從 ONTAP Select 9.14.1 開始,不再支援 Deploy VMware vCenter 外掛程式。
更新 ONTAP Select Deploy 支援:: 如果您目前執行的 ONTAP Select Deploy 9.14.1 版本低於 9.14.1P2，則應盡快升級至 ONTAP Select Deploy 9.14.1P2。如需詳細資訊，請參閱 link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["ONTAP Select 9.14.1 版本說明"^]。
增強型 VMware ESXi 支援:: ONTAP Select 9.14.1 包含對 VMware ESXi 8.0 U2 的支援。




== ONTAP Select 9.13.1

支援透過 TCP 的 NVMe:: 升級到 ONTAP Select 9.13.1 時，您必須擁有支援 NVMe over TCP 的新授權。首次從 9.13.1 版本部署 ONTAP Select 時，此授權會自動包含在內。
更新 VMware ESXi 支援:: 從 ONTAP 9.13.1 開始，硬體版本 4 及更新版本支援 VMware ESXi 8.0.1 GA（組建 20513097）。
更新 ONTAP Select Deploy 支援:: 截至 2024 年 4 月,ONTAP Select Deploy 9.13.1 已不再在 NetApp 支援網站上提供。如果您正在執行 ONTAP Select Deploy 9.13.1,則應盡快升級至 ONTAP Select Deploy 9.14.1P2。如需詳細資訊，請參閱 link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["ONTAP Select 9.14.1 版本說明"^]。




== ONTAP Select 9.12.1

ONTAP Select 9.12.1 受益於目前 ONTAP 核心產品版本的大部分新開發成果。它不包含任何 ONTAP Select 特有的新功能或改進。

截至 2024 年 4 月,ONTAP Select Deploy 9.12.1 已不再在 NetApp 支援網站上提供。如果您正在執行 ONTAP Select Deploy 9.12.1,則應盡快升級至 ONTAP Select Deploy 9.14.1P2。如需詳細資訊，請參閱 link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2886733["ONTAP Select 9.14.1 版本說明"^]。



== ONTAP Select 9.11.1

增強型 VMware ESXi 支援:: ONTAP Select 9.11.1 包含對 VMware ESXi 7.0 U3C 的支援。
支援 VMware NSX-T:: ONTAP Select 9.10.1 及更高版本已通過 VMware NSX-T 3.1.2 版本的認證。當使用 OVA 檔案和 ONTAP Select Deploy 管理實用程式部署 ONTAP Select 單節點叢集時，NSX-T 不存在任何功能問題或缺陷。但是，當使用 NSX-T 部署 ONTAP Select 多節點叢集時，請注意 ONTAP Select 9.11.1 的以下限制：
+
--
* 網路連線檢查器
+
透過 Deploy CLI 提供的網路連線檢查程式在針對以 NSX-T 為基礎的網路執行時會失敗。



--
不再支援 KVM Hypervisor::
+
--
* 從 ONTAP Select 9.10.1 開始、您將無法再在 KVM Hypervisor 上部署新叢集。
* 從 ONTAP Select 9.11.1 開始，除了離線和刪除功能之外，現有 KVM 叢集和主機的所有管理功能均不再可用。
+
NetApp 強烈建議客戶規劃並執行從 ONTAP Select for KVM 到任何其他 ONTAP 平台（包括 ONTAP Select for ESXi）的完整資料遷移。如需更多資訊，請參閱 https://mysupport.netapp.com/info/communications/ECMLP2877451.html["EOA 通知"^]



--




== ONTAP Select 9.10.1

支援 VMware NSX-T:: ONTAP Select 9.10.1 已通過 VMware NSX-T 3.1.2 版本的認證。當使用 OVA 檔案和 ONTAP Select Deploy 管理實用程式部署 ONTAP Select 單節點叢集時，NSX-T 不存在任何功能問題或缺陷。但是，當 NSX-T 與 ONTAP Select 多節點叢集配合使用時，應注意以下要求和限制：
+
--
* 叢集 MTU
+
為了應對額外的開銷，您必須在部署叢集之前手動將叢集 MTU 大小調整為 8800。VMware 建議在使用 NSX-T 時預留 200 位元組的緩衝區。

* 網路 4x10Gb 配置
+
對於在配置了四個 NIC 的 VMware ESXi 主機上的 ONTAP Select 部署，Deploy 公用程式會提示您遵循最佳實務做法，將內部流量分散到兩個不同的連接埠群組，並將外部流量分散到兩個不同的連接埠群組。但是，當使用覆疊網路時，此組態無法運作，您應該忽略此建議。在這種情況下，您應該只使用一個內部連接埠群組和一個外部連接埠群組。

* 網路連線檢查器
+
透過 Deploy CLI 提供的網路連線檢查程式在針對以 NSX-T 為基礎的網路執行時會失敗。



--
不再支援 KVM Hypervisor:: 從 ONTAP Select 9.10.1 開始,您將無法再在 KVM Hypervisor 上部署新叢集。但是,如果您將叢集從先前的版本升級到 9.10.1,仍然可以使用 Deploy 公用程式來管理叢集。




== ONTAP Select 9.9.1

處理器系列支援:: 從 ONTAP Select 9.9.1 開始,ONTAP Select 僅支援 Intel Xeon Sandy Bridge 或更新版本的 CPU 型號。
更新 VMware ESXi 支援:: ONTAP Select 9.9.1 增強了對 VMware ESXi 的支援。現在支援以下版本：
+
--
* ESXi 7.0 U2
* ESXi 7.0 U1


--




== ONTAP Select 9.8

高速介面:: 高速介面功能透過提供 25G（25GbE）和 40G（40GbE）兩種選項來增強網路連線。為了在使用這些更高速度時獲得最佳效能，您應該遵循 ONTAP Select 文件中所述的連接埠對應組態最佳實務做法。
更新 VMware ESXi 支援:: ONTAP Select 9.8 在對 VMware ESXi 的支援方面有兩項變更。
+
--
* 支援 ESXi 7.0（GA 組建 15843807 及更新版本）
* 不再支援 ESXi 6.0


--

