---
sidebar: sidebar 
permalink: reference_plan_ots_storage.html 
keywords: plan, planning, storage, software raid, hardware raid, raid, nvme 
summary: 關於 ONTAP Select 主機儲存設備，有幾個規劃問題需要考慮。 
---
= ONTAP Select 儲存和 RAID 注意事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
關於 ONTAP Select 主機儲存設備，有幾個規劃問題需要考慮。


NOTE: 本文概述了 ESXi 和 KVM 主機的外部儲存支援資訊。如需更多資訊，請參閱link:reference_plan_ots_vnas.html["VMware ESXi 需求"]和link:reference_plan_ots_kvm.html["KVM 需求"]。



[[hardware-raid-controller-requirements]]
== 硬體 RAID 控制器需求

部署 ONTAP Select 的虛擬機器管理程式主機上的 RAID 控制器必須符合幾個要求。


NOTE: 執行 ONTAP Select 的主機在使用硬體 RAID 控制器或 ONTAP Select 提供的軟體 RAID 功能時，需要本機實體磁碟機。如果使用 ONTAP Select vNAS 解決方案存取外部儲存設備，則不會使用本機 RAID 控制器和軟體 RAID 功能。

RAID 控制器的最低要求包括：

* 12 Gbps 處理量
* 512 MB 內建電池備援或快閃記憶體 （SuperCAP） 快取
* 已設定為回寫模式：
+
** 啟用故障恢復模式為「直寫」（如果支援）
** 啟用「永遠預先讀取」原則 （如果支援）


* RAID 控制器後面的所有本機磁碟應配置為單一 RAID 群組；如有需要，可使用多個 RAID 控制器：
+
** 停用 RAID 群組的本機磁碟機快取，這對於保持資料完整性至關重要。


* 請依照下列準則執行 LUN 設定：
+
** 如果 RAID 群組的大小超過 64TB 的最大 LUN 大小，請設定多個大小相等的 LUN，以使用 RAID 群組內的所有可用儲存空間。
** 如果 RAID 群組的大小小於 64TB 的最大 LUN 大小，則設定一個 LUN 來佔用 RAID 群組內的所有可用儲存空間。






[[software-raid-requirements]]
== 軟體 RAID 需求

在虛擬機器管理程式上部署 ONTAP Select 叢集時，您可以使用 ONTAP Select 提供的軟體 RAID 功能，而非本機硬體 RAID 控制器。在使用軟體 RAID 部署叢集之前，請查看以下要求和限制。



[[general-requirements]]
=== 一般要求

軟體 RAID 部署環境必須符合以下核心要求：

* VMware ESXi 8.0 GA（組建 20513097）或更新版本
* ONTAP Select 進階授權或更高版本
* 僅限本機 SSD 磁碟機
* 將系統磁碟與根 Aggregate 和資料 Aggregate 分離
* 主機上沒有硬體 RAID 控制器



NOTE: 如果存在硬體 RAID 控制器，請參閱 link:concept_stor_concepts_chars.html["深入探討儲存設備"] 部分以了解其他設定需求。



[[esxi-specific-requirements]]
=== ESXi 特定需求

* VMware ESXi 8.0 GA（組建 20513097）或更新版本
* 不支援 VMware VMotion、HA 和 DRS
* 您無法在已從 ONTAP Select 9.4 或更早版本升級的節點上使用軟體 RAID。如果是這種情況，您需要為軟體 RAID 部署建立新節點。




[[kvm-specific-requirements]]
=== KVM 特定需求

此外，軟體套件配置也有特定要求。請參閱 link:https://docs.netapp.com/us-en/ontap-select/kvm-host-configuration-and-preparation-checklist.html#prepare-linux-server["Linux 伺服器的準備工作"] 步驟以了解更多資訊。

KVM 的媒體期望:: 所使用的 SSD 快閃儲存設備必須符合以下附加要求：
+
--
* SSD 裝置必須透過下列方法準確且持續地向 Linux 主機報告自身狀態：
+
** # cat /sys/block/<device>/queue/rotational
+
這些命令報告的值必須為 '0'。



* 預計這些設備將連接到 HBA 卡，或在某些情況下，連接到配置為 JBOD 模式的 RAID 控制器。使用 RAID 控制器時，設備功能必須透過主機傳遞，不得疊加任何 RAID 功能。在 JBOD 模式下使用 RAID 控制器時，您應查閱 RAID 文件或根據需要聯絡供應商，以確保設備報告的轉速為 '0'。
* 有兩個獨立的儲存元件：
+
** 虛擬機器儲存設備
+
這是一個 LVM 池（儲存池），其中包含用於託管 ONTAP Select 虛擬機器的系統資料。LVM 池必須由高耐久性快閃記憶體設備提供支持，可以是 SAS、SATA 或 NVMe 設備。建議使用 NVMe 設備以獲得更好效能。

** 資料磁碟
+
這是一組用於資料管理的 SAS 或 SATA SSD 磁碟機。SSD 裝置應為企業級且經久耐用。不支援 NVMe 介面。



* 所有裝置都必須格式化為 512BPS。


--




[[ontap-select-node-configuration]]
=== ONTAP Select 節點組態

您必須如下設定每個 ONTAP Select 節點和 Hypervisor 主機，以將系統磁碟與根 Aggregate 和資料 Aggregate 分開：

* 建立系統儲存資源池您必須為 ONTAP Select 系統資料建立儲存資源池。您必須在設定 ONTAP Select 節點時附加儲存資源池。
* 連接必要的實體磁碟 虛擬機器管理程式主機必須連接並可用所需的 SSD 磁碟，以供 ONTAP Select 虛擬機器使用。這些磁碟機保存根 Aggregate 和資料 Aggregate。您必須在設定 ONTAP Select 節點時連接儲存磁碟。




[[storage-capacity-restrictions]]
== 儲存容量限制

在規劃 ONTAP Select 部署時，您應該了解與儲存分配和使用相關的限制。

最重要的儲存限制如下所示。您還應查看 link:https://mysupport.netapp.com/matrix/["互通性對照表工具"^] 以獲取更詳細的資訊。


TIP: ONTAP Select 對儲存分配和使用實施了多項限制。在部署 ONTAP Select 叢集或購買授權之前，您應該熟悉這些限制。如需詳細資訊，請參閱link:concept_lic_evaluation.html["授權"]章節。



[[calculate-raw-storage-capacity]]
=== 計算原始儲存容量

ONTAP Select 儲存容量對應於連接到 ONTAP Select 虛擬機器的虛擬資料磁碟和根磁碟的總允許大小。分配容量時應考慮此因素。



[[minimum-storage-capacity-for-a-single-node-cluster]]
=== 單節點叢集的最小儲存容量

單節點叢集中分配給節點的儲存資源池最小大小為：

* 評估：500 GB
* 正式作業：1.0 TB


生產部署的最低分配包括 1 TB 用於使用者資料，以及大約 266 GB 供各種 ONTAP Select 內部程序使用，這被視為必要的額外負荷。



[[minimum-storage-capacity-for-a-multi-node-cluster]]
=== 多節點叢集的最小儲存容量

多節點叢集中每個節點分配的儲存資源池最小大小為：

* 評估：1.9 TB
* 正式作業：2.0 TB


生產部署的最低分配包括 2 TB 用於使用者資料，以及大約 266 GB 供各種 ONTAP Select 內部程序使用，這被視為必要的額外負荷。

[NOTE]
====
HA 配對中的每個節點都必須具有相同的儲存容量。

在估算高可用性（HA）配對的儲存容量時，必須考慮到所有 Aggregate（根 Aggregate 和資料 Aggregate）都是鏡像的。因此，Aggregate 中的每個 Plex 消耗的儲存空間相等。

例如，當建立 2TB Aggregate 時，它會將 2TB 分配給兩個 plex 執行個體（plex0 為 2TB、plex1 為 2TB），或總授權儲存容量的 4TB。

====


[[storage-capacity-and-multiple-storage-pools]]
=== 儲存容量和多個儲存資源池

使用本機直連儲存設備、VMware vSAN 或外部儲存陣列時，您可以將每個 ONTAP Select 節點設定為使用高達 400 TB 的儲存設備。但是，在使用直連儲存設備或外部儲存陣列時，單一儲存資源池的大小上限為 64 TB。因此，如果您打算在這些情況下使用超過 64 TB 的儲存設備，則必須配置多個儲存資源池，如下所示：

* 在叢集建立過程中指派初始儲存資源池
* 透過分配一個或多個額外的儲存資源池來增加節點儲存空間



NOTE: 每個儲存池中都預留了 2% 的緩衝區，無需容量授權。除非您指定容量上限，否則 ONTAP Select 不會使用此儲存空間。如果您指定了容量上限，則 ONTAP Select 會使用該儲存空間量，除非指定的量落在 2% 緩衝區範圍內。此緩衝區用於防止在嘗試分配儲存池中所有空間時偶爾發生的錯誤。



[[storage-capacity-and-vmware-vsan]]
=== 儲存容量和 VMware vSAN

使用 VMware vSAN 時，資料儲存容量可以大於 64 TB。但是，在建立 ONTAP Select 叢集時，初始分配容量上限為 64 TB。叢集建立完成後，您可以從現有的 vSAN 資料儲存中指派額外的儲存空間。ONTAP Select 可使用的 vSAN 資料儲存容量取決於虛擬機器儲存策略的設定。



[[best-practices]]
=== 最佳實務

關於 Hypervisor 核心硬體，您應該考慮以下建議：

* 單一 ONTAP Select Aggregate 中的所有磁碟機都應該是相同類型。例如、您不應在同一個 Aggregate 中混用 HDD 和 SSD 磁碟機。




[[additional-disk-drive-requirements-based-on-the-platform-license]]
== 根據平台授權的其他磁碟機需求

您選擇的磁碟機會根據平台授權方案而受到限制。


NOTE: 磁碟機要求適用於使用本機 RAID 控制器和磁碟機以及軟體 RAID 的情況。這些要求不適用於透過 ONTAP Select vNAS 解決方案存取的外部儲存設備。

.標準
* 8 至 60 個內建 HDD（NL-SAS、SATA、10K SAS）


.高級
* 8 至 60 個內建 HDD（NL-SAS、SATA、10K SAS）
* 4 至 60 個內建 SSD


.高級 XL
* 8 至 60 個內建 HDD（NL-SAS、SATA、10K SAS）
* 4 至 60 個內建 SSD
* 4 到 14 個內部 NVMe



NOTE: 進階授權（僅限 SSD）和進階 XL 授權（SSD 或 NVMe）支援使用本機 DAS 磁碟機的軟體 RAID。



[[nvme-drives-with-software-raid]]
== 採用軟體 RAID 的 NVMe 磁碟機

您可以設定軟體 RAID 以使用 NVMe SSD 磁碟機。您的環境必須符合以下要求：

* ONTAP Select 搭配支援的 Deploy 管理公用程式
* Premium XL 平台授權方案或 90 天評估授權
* VMware ESXi 8.0 或更新版本
* 符合規格 1.0 或更新版本的 NVMe 裝置


使用 NVMe 磁碟機之前，您需要手動設定它們。如需詳細資訊，請參閱 link:task_chk_nvme_configure.html["設定主機以使用 NVMe 磁碟機"]。
