---
sidebar: sidebar 
permalink: reference_plan_ots_hardware.html 
keywords: plan, planning, vmware, hardware, hardware requirements 
summary: 您應該考慮與 VMware 環境相關的幾個硬體需求和規劃問題。 
---
= ONTAP Select VMware 虛擬機器管理程式和硬體注意事項
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您應該考慮與 VMware 環境相關的幾個硬體需求和規劃問題。



[[hypervisor-requirements]]
== Hypervisor 需求

ONTAP Select 運作所依賴的 Hypervisor 有幾項相關要求。


NOTE: 您應檢閱 link:reference_release_notes.html["ONTAP Select 發行說明"] 以瞭解任何其他已知的限制或約束。



[[vmware-licensing]]
=== VMware 授權

若要部署 ONTAP Select 叢集，您的組織必須擁有適用於執行 ONTAP Select 的 Hypervisor 主機的有效 VMware vSphere 授權。您應該使用適合您部署環境的授權。



[[software-compatibility]]
=== 軟體相容性

您可以在 KVM 和 ESXi Hypervisor 上部署 ONTAP Select。

[role="tabbed-block"]
====
.KVM
--
ONTAP Select 支援以下 KVM Hypervisor 版本：

* Red Hat Enterprise Linux (RHEL) 10.1、10.0、9.7、9.6、9.5、9.4、9.2、9.1、9.0、8.8、8.7 和 8.6 上的 KVM
* KVM on Rocky Linux 10.1、10.0、9.7、9.6、9.5、9.4、9.3、9.2、9.1、9.0、8.9、8.8、8.7 和 8.6


--
.ESXi
--
ONTAP Select 支援以下 ESXi Hypervisor 版本：

* VMware ESXi 9.0
* VMware ESXi 8.0 U3
* VMware ESXi 8.0 U2
* VMware ESXi 8.0 U1（build 21495797）
* VMware ESXi 8.0 GA（組建 20513097）



NOTE: 只要 VMware 也繼續支援相同版本，NetApp 就會在已識別的 ESXi 版本上支援 ONTAP Select。


NOTE: ESXi 7.0 GA 已停止提供服務。如果您有使用此版本的 ONTAP Select 叢集，則必須按照 https://mysupport.netapp.com/matrix["互通性對照表工具（IMT）"^]升級到受支援的版本。

--
====


[[vmware-vcenter-and-standalone-esxi-hosts]]
=== VMware vCenter 和獨立 ESXi 主機

如果 ESXi Hypervisor 主機由 vCenter 伺服器管理，則必須使用 vCenter 認證將該主機註冊至 Deploy 管理公用程式。您不能使用 ESXi 認證將該主機註冊為獨立主機。



[[core-hardware-requirements]]
== 核心硬體需求

部署 ONTAP Select 的實體 Hypervisor 主機必須符合多項硬體需求。您可以選擇任何平台作為 Hypervisor 主機，只要它符合最低硬體需求即可。以下供應商提供支援的硬體平台：Cisco、Dell、HP、Fujitsu、Lenovo 和 Supermicro。


NOTE: 從 ONTAP Select 9.9.1 開始，僅支援基於 Intel Xeon Sandy Bridge 或更高版本的 CPU 型號。

如需詳細資訊，請參閱 https://mysupport.netapp.com/matrix["互通性對照表工具，window=_blank"]。



[[basic-hardware-requirements]]
=== 基本硬體需求

無論節點執行個體類型或授權方案為何，所有平台都適用數個通用的硬體需求。

.處理器
支援的微處理器包括適用於伺服器的 Intel Xeon 處理器，詳情請參閱 link:https://www.intel.com/content/www/us/en/products/processors/xeon/view-all.html?Processor+Type=1003["Intel Xeon 處理器，window=_blank"]。


NOTE: ONTAP Select 不支援 Advanced Micro Devices（AMD）處理器。

.乙太網路組態
根據叢集大小，有數種支援的乙太網路組態。

[cols="2,3,3"]
|===
| 叢集大小 | 最低需求 | 建議需求 


| 單節點叢集 | 2 x 1GbE | 2 x 10GbE 


| 雙節點叢集或 MetroCluster SDS | 4 x 1GbE 或 1 x 10GbE | 2 x 10GbE 


| 四節點、六節點、八節點、十節點或十二節點叢集 | 2 x 10GbE | 4 x 10GbE 或 2 x 25/40GbE 
|===


[[additional-hardware-requirements-based-on-the-instance-type]]
=== 根據執行個體類型而定的其他硬體需求

根據節點執行個體類型，還有一些額外的硬體需求。

如需詳細資訊，請參閱 link:concept_lic_platforms.html["了解平台授權方案"]。

[cols="a1,a2,a2,a2"]
|===
| 節點大小 | CPU 核心 | 記憶體 | 所需的平台授權方案 


| 小型 | 六個或更多實體核心，其中四個保留給 ONTAP Select 使用。 | 24GB 或以上，其中 16GB 保留給 ONTAP Select | 標準版、進階版或進階 XL 版 


| 中 | 十個或更多實體核心，其中八個保留給 ONTAP Select 使用。 | 72GB 或更大，其中 64GB 保留給 ONTAP Select | Premium 或 Premium XL 


| 大型 | 至少 18 個實體核心，其中 16 個保留給 ONTAP Select | 136GB 或更大，其中 128GB 保留給 ONTAP Select | 高級 XL 
|===

NOTE: 根據平台授權，還有其他磁碟需求。如需詳細資訊，請參閱 link:reference_plan_ots_storage.html["儲存設備與 RAID"]。
