---
sidebar: sidebar 
permalink: reference_plan_ots_mcc_sds.html 
keywords: plan, planning, metrocluster, metrocluster sds 
summary: 在規劃 ONTAP Select 部署時，您應該考慮 MetroCluster SDS 的幾個要求。 
---
= 準備部署 ONTAP Select MetroCluster SDS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
MetroCluster SDS 是建立雙節點 ONTAP Select 叢集時的一個配置選項。它類似於遠端辦公室/分支機構（ROBO）部署。這種增強型雙節點部署提供了更多使用案例場景。在準備部署 MetroCluster SDS 時，您應該了解其要求和限制。

在部署 MetroCluster SDS 之前，請確認符合以下要求。

.授權
每個節點必須擁有高級版或更高級別的 ONTAP Select 授權。

.Hypervisor 平台
MetroCluster SDS 可以部署在與 ROBO 環境中雙節點叢集支援的 VMware ESXi 和 KVM 虛擬機器管理程式相同的平台上。

[NOTE]
====
從 ONTAP Select 9.14.1 開始，已復原對 KVM Hypervisor 的支援。先前，ONTAP Select 9.10.1 移除了在 KVM Hypervisor 上部署新叢集的支援，而 ONTAP Select 9.11.1 則移除了對現有 KVM 叢集和主機的管理支援（離線或刪除除外）。

====
.網路組態
參與站台之間需要第 2 層連線。支援 10GbE 和 1GbE，包括以下組態：

* 1 x 10GbE
* 4 x 1GbE



NOTE: 資料服務連接埠和互連連接埠必須連接至同一個第一台交換器。

.節點之間的延遲
兩個節點之間的網路必須支援 5 毫秒的平均延遲，並允許 5 毫秒的周期性抖動。在部署叢集之前，必須按照 link:concept_nw_concepts_chars.html["深入探討網路"] 節所述的步驟測試網路。

.Mediator 服務
與所有雙節點 ONTAP Select 叢集一樣，Deploy 虛擬機器中包含一個獨立的中介服務，用於監控節點並協助管理故障。借助 MetroCluster SDS 提供的增強距離，網路拓撲中會建立三個獨立的站點。中介服務與節點之間的連結延遲應為往返 125 毫秒或更低。

.儲存
支援使用 HDD 和 SSD 磁碟的直接連接儲存設備（DAS）。也支援 vNAS，包括外部儲存陣列和 VMware 環境中的 vSAN。


NOTE: 部署 MetroCluster SDS 時，不能在分散式或「擴充」拓樸中使用 vSAN。

.指派給 Deploy 的靜態 IP 位址
您必須為 Deploy 管理公用程式指派靜態 IP 位址。此要求適用於管理一個或多個 ONTAP Select 雙節點叢集的所有 Deploy 執行個體。
