---
sidebar: sidebar 
permalink: task_cli_connectivity.html 
keywords: administer, administering, cli, connectivity, network connectivity, network checker 
summary: 您可以測試內部叢集網路上兩個或多個 ONTAP Select 節點之間的網路連線。通常，您會在部署多節點叢集之前執行此測試，以偵測可能導致操作失敗的問題。 
---
= 確認 ONTAP Select 節點之間的網路連線
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以測試內部叢集網路上兩個或多個 ONTAP Select 節點之間的網路連線。通常，您會在部署多節點叢集之前執行此測試，以偵測可能導致操作失敗的問題。

.開始之前
測試中包含的所有 ONTAP Select 節點都必須進行配置並通電。

.關於此任務
每次啟動測試時，背景都會建立新的程序執行，並指派一個唯一的執行識別碼。一次只能有一個執行處於作用中狀態。

測試有兩種控制其運作的模式：

* 快速此模式執行基本的非中斷性測試。它會執行 PING 測試，以及網路 MTU 大小和 vSwitch 的測試。
* 擴展模式會對所有冗餘網路路徑執行更全面的測試。如果在正在運行的 ONTAP Select 叢集上執行此模式，可能會影響叢集的效能。



NOTE: 建議您在建立多節點叢集之前，一律先執行快速測試。快速測試成功完成後，您可以根據正式作業需求選擇性地執行延伸測試。

.步驟
. 使用管理員帳戶 Sign in 至部署實用程式 CLI。
. 顯示網路連線檢查器的目前執行情況，並確認沒有正在執行的檢查器：
+
`network connectivity-check show`

. 啟動網路連線檢查程式，並記下命令輸出中的執行識別碼：
+
`network connectivity-check start -host-names HOSTNAMES -vswitch-type VSWITCH_TYPE-mode MODE`

+
範例

+
[listing]
----
network connectivity-check start -host-names 10.234.81.14
10.234.81.15 -vswitch-type StandardVSwitch -mode quick
----
. 根據執行識別碼監控網路連線檢查程式的進度：
+
`network connectivity-check show -run-id RUN_ID`



.完成後
網路連線檢查器通常會清理新增至 ONTAP-Internal 連接埠群組中的所有暫存連接埠和 IP 位址。但是，如果連線檢查器未能移除暫存連接埠，則必須手動執行清理操作，方法是重新執行帶有選項的 CLI 命令 `-mode cleanup`。如果您未從 ONTAP-Internal 連接埠群組中移除暫存連接埠，則可能無法成功建立 ONTAP Select 虛擬機器。
