---
sidebar: sidebar 
permalink: task_cli_deploy_recover_two_node.html 
keywords: administer, administering, cli, two node cluster, recover, recovering 
summary: 如果 ONTAP Select Deploy 公用程式發生故障或因某種原因不可用，您將失去管理 ONTAP Select 節點和叢集的能力。此外，所有雙節點叢集都將失去 HA 功能，因為 Deploy 中包含的中介服務不可用。如果發生無法復原的故障，您必須復原 Deploy 公用程式執行個體才能還原管理和 HA 功能。 
---
= 恢復雙節點叢集的 ONTAP Select Deploy 公用程式
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
如果 ONTAP Select Deploy 公用程式發生故障或因某種原因不可用，您將失去管理 ONTAP Select 節點和叢集的能力。此外，所有雙節點叢集都將失去 HA 功能，因為 Deploy 中包含的中介服務不可用。如果發生無法復原的故障，您必須復原 Deploy 公用程式執行個體才能還原管理和 HA 功能。



[[prepare-to-recover-the-deploy-utility]]
== 準備恢復 Deploy 公用程式

在嘗試還原 Deploy 公用程式執行個體之前，您需要做好準備以確保成功。您必須熟悉若干管理程序並擁有所需資訊。

.步驟
. 確認您可以在虛擬機器管理程式環境中安裝 ONTAP Select Deploy 公用程式的新執行個體。
+
link:task_install_deploy.html["了解如何安裝 ONTAP Select Deploy 公用程式"]

. 確認您可以登入 ONTAP Select 叢集並存取 ONTAP 叢集 shell（CLI）。
. 請確定您是否擁有包含 ONTAP Select 雙節點叢集的故障 Deploy 公用程式執行個體的組態資料備份。您可能擁有一個不包含該叢集的備份。
. 根據所使用的復原程序，驗證是否可以還原 Deploy 組態資料的備份。
+
link:task_cli_migrate_deploy.html#step-3-restore-the-deploy-configuration-data-to-the-new-virtual-machine["了解如何將 Deploy 組態資料還原到新的虛擬機器"]

. 您擁有發生故障的原始 Deploy 公用程式虛擬機器的 IP 位址。
. 確定使用的是 Capacity Pools 授權還是 Capacity Tiers 授權。如果使用的是 Capacity Pools 授權，則在復原或還原 Deploy 執行個體後，必須重新安裝每個 Capacity Pool 授權。
. 決定在復原 ONTAP Select Deploy 公用程式執行個體時要使用哪個程序。您的決定取決於您是否擁有包含 ONTAP Select 雙節點叢集之原始故障 Deploy 公用程式的組態資料備份。
+
[cols="35,65"]
|===
| 您是否有包含雙節點叢集的 Deploy 備份？ | 使用還原程序… 


| 是的 | <<restore-deploy-backup,使用組態備份還原 Deploy 公用程式執行個體>> 


| 否 | <<restore-and-recover-deploy,重新設定並還原 Deploy 實用程式執行個體>> 
|===




[[restore-a-deploy-utility-instance-using-a-configuration-backup]]
[[restore-deploy-backup]]
== 使用組態備份還原 Deploy 公用程式執行個體

如果您有包含雙節點叢集的故障 Deploy 公用程式執行個體的備份，則可以將組態資料還原到新的 Deploy 虛擬機器執行個體。然後，您必須透過對 ONTAP Select 叢集中的兩個節點執行其他組態來完成還原。

.開始之前
從包含雙節點叢集的原始故障 Deploy 虛擬機器備份組態資料。您必須能夠 Sign in 雙節點叢集的 ONTAP CLI，並知道兩個節點的 ONTAP 名稱。

.關於此任務
由於您還原的組態備份包含雙節點叢集，因此 mediator iSCSI 目標和信箱會在新的 Deploy 公用程式虛擬機器中重新建立。

.步驟
. 準備一個新的 ONTAP Select Deploy 公用程式執行個體：
+
.. 安裝新的 Deploy 公用程式虛擬機器。
.. 將 Deploy 組態從先前的備份還原到新的虛擬機器。
+
如需安裝與還原程序的詳細資訊、請參閱相關工作。



. Sign in 至 ONTAP Select 雙節點叢集的 ONTAP 命令列介面。
. 進入進階權限模式：
+
[source, cli]
----
set adv
----
. 如果新 Deploy 虛擬機器的 IP 位址與原 Deploy 虛擬機器的 IP 位址不同，請移除舊的 Mediator iSCSI 目標並新增目標：
+
[source, cli]
----
storage iscsi-initiator remove-target -node * -target-type mailbox
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node2_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
此  `<ip_address>` 參數是新 Deploy 虛擬機器的 IP 位址。

+
這些命令允許 ONTAP Select 節點發現新的 Deploy 公用程式虛擬機器上的信箱磁碟。

. 確定 mediator 磁碟的名稱：
+
[source, cli]
----
disk show -container-type mediator
----
. 將信箱磁碟指派給兩個節點：
+
[source, cli]
----
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
----
. 確認已啟用儲存容錯移轉：
+
[source, cli]
----
storage failover show
----


.完成後
如果您使用 Capacity Pools 授權，請重新安裝每個 Capacity Pool 授權。如需其他詳細資料，請參閱link:task_adm_licenses.html#reinstall-a-capacity-pool-license["重新安裝 Capacity Pool 授權"]。



[[reconfigure-and-recover-a-deploy-utility-instance]]
[[restore-and-recover-deploy]]
== 重新設定並還原 Deploy 實用程式執行個體

如果您沒有包含雙節點叢集的故障 Deploy 公用程式執行個體的備份，請在新的 Deploy 虛擬機器中設定 mediator iSCSI 目標和 mailbox。然後，透過對 ONTAP Select 叢集中的兩個節點進行其他組態設定來完成還原。

.開始之前
請確認您已取得新 Deploy 公用程式執行個體的中介目標名稱。您必須能夠 Sign in 雙節點叢集的 ONTAP CLI，並且知道這兩個節點的 ONTAP 名稱。

.關於此任務
即使新的 Deploy 虛擬機器不包含雙節點叢集，您也可以選擇將組態備份還原到該虛擬機器。由於還原作業不會重新建立雙節點叢集，因此您必須透過 Deploy 的 ONTAP Select 線上文件網頁，手動將中介 iSCSI 目標和信箱新增至新的 Deploy 公用程式執行個體。您必須能夠 Sign in 雙節點叢集，並且知道這兩個節點的 ONTAP 名稱。


NOTE: 復原程序的目標是將雙節點叢集還原至健全狀態，以便執行正常的 HA 接管和恢復作業。

.步驟
. 準備一個新的 ONTAP Select Deploy 公用程式執行個體：
+
.. 安裝新的 Deploy 公用程式虛擬機器。
.. 您也可以選擇將 Deploy 組態從先前的備份還原至新的虛擬機器。
+
如果還原先前的備份，新的 Deploy 執行個體將不包含雙節點叢集。如需安裝和還原程序的詳細資訊，請參閱相關資訊一節。



. Sign in 至 ONTAP Select 雙節點叢集的 ONTAP 命令列介面。
. 進入進階權限模式：
+
[source, cli]
----
set adv
----
. 取得中介器 iSCSI 目標名稱：
+
[source, cli]
----
storage iscsi-initiator show -target-type mailbox
----
. 存取新 Deploy 公用程式虛擬機器上的線上說明文件網頁，並使用 admin 帳戶 Sign in ：
+
`\http://<ip_address>/api/ui`

+
您必須使用 Deploy 虛擬機器的 IP 位址。

. 選取 *Mediator*，然後選取 *GET /mediators*。
. 選擇 *Try it out!* 以顯示 Deploy 維護的中介器清單。
+
記下所需中介執行個體的 ID。

. 選擇 *Mediator*，然後選擇 *POST*。
. 請提供 mediator_id 的值。
. 選擇  `iscsi_target` 旁邊的 *Model*，然後填入名稱值。
+
使用目標名稱作為 iqn_name 參數。

. 選擇 *Try it out!* 以建立中介 iSCSI 目標。
+
如果請求成功，您將收到 HTTP 狀態碼 200。

. 如果新 Deploy 虛擬機器的 IP 位址與原 Deploy 虛擬機器的 IP 位址不同，則必須使用 ONTAP CLI 刪除舊的中介 iSCSI 目標並新增目標：
+
[source, cli]
----
storage iscsi-initiator remove-target -node * -target-type mailbox
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node1_name> -label mediator -target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
[source, cli]
----
storage iscsi-initiator add-target -node <node2_name> -label mediator-target-type mailbox -target-portal <ip_address> -target-name <target>
----
+
此  `<ip_address>` 參數是新 Deploy 虛擬機器的 IP 位址。

+
這些命令允許 ONTAP Select 節點發現新的 Deploy 公用程式虛擬機器上的信箱磁碟。

. 確定 mediator 磁碟的名稱：
+
[source, cli]
----
disk show -container-type mediator
----
. 將信箱磁碟指派給兩個節點：
+
[source, cli]
----
disk assign -disk <mediator-disk1-name> -owner <node1-name>

disk assign -disk <mediator-disk2-name> -owner <node2-name>
----
. 確認已啟用儲存容錯移轉：
+
[source, cli]
----
storage failover show
----


.完成後
如果您使用 Capacity Pools 授權，請重新安裝每個 Capacity Pool 授權。如需其他詳細資料，請參閱link:task_adm_licenses.html#reinstall-a-capacity-pool-license["重新安裝 Capacity Pool 授權"]。
